apiVersion: v1
kind: Service
metadata:
  name: myjavaapp-service # 资源对象名称
spec:
  # 没指定type时，默认是ClusterIP类型的服务，即集群内部的服务；
  # NodePort表示节点端口类型的服务，该服务可对外提供服务，公网可以访问，需要配置 nodePort
  type: NodePort 
  selector:
    app: myjavaapp # 对应deployment下的 spec.selector.matchLabels.app值，通过标签选择对应的字段
  ports:
  - protocol: TCP
    port: 80 # 该service对外公开的端口
    targetPort: 8080 # pod的端口
    nodePort: 31188 # 节点端口必须在30000~32767之间


